// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion7

type TunnelServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (TunnelService_ConnectClient, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type tunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelServiceClient(cc grpc.ClientConnInterface) TunnelServiceClient {
	return &tunnelServiceClient{cc}
}

func (c *tunnelServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (TunnelService_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &TunnelService_ServiceDesc.Streams[0], "/tunnel.TunnelService/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &tunnelServiceConnectClient{stream}
	return x, nil
}

type TunnelService_ConnectClient interface {
	Send(*TunnelFrame) error
	Recv() (*TunnelFrame, error)
	grpc.ClientStream
}

type tunnelServiceConnectClient struct {
	grpc.ClientStream
}

func (x *tunnelServiceConnectClient) Send(m *TunnelFrame) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tunnelServiceConnectClient) Recv() (*TunnelFrame, error) {
	m := new(TunnelFrame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tunnelServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/tunnel.TunnelService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelServiceClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, "/tunnel.TunnelService/GetMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type TunnelServiceServer interface {
	Connect(TunnelService_ConnectServer) error
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
}

type UnimplementedTunnelServiceServer struct {
}

func (UnimplementedTunnelServiceServer) Connect(TunnelService_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedTunnelServiceServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedTunnelServiceServer) GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}

func RegisterTunnelServiceServer(s grpc.ServiceRegistrar, srv TunnelServiceServer) {
	s.RegisterService(&TunnelService_ServiceDesc, srv)
}

func _TunnelService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServiceServer).Connect(&tunnelServiceConnectServer{stream})
}

type TunnelService_ConnectServer interface {
	Send(*TunnelFrame) error
	Recv() (*TunnelFrame, error)
	grpc.ServerStream
}

type tunnelServiceConnectServer struct {
	grpc.ServerStream
}

func (x *tunnelServiceConnectServer) Send(m *TunnelFrame) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tunnelServiceConnectServer) Recv() (*TunnelFrame, error) {
	m := new(TunnelFrame)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TunnelService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tunnel.TunnelService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tunnel.TunnelService/GetMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).GetMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var TunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.TunnelService",
	HandlerType: (*TunnelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _TunnelService_GetStatus_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _TunnelService_GetMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _TunnelService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/tunnel.proto",
}
